# Generated by pretty-terminal — minimal, no-background-box Powerlevel10k config.
# Prompt style: icon  dir  git
#               ❯
# No colored background segments — just colored text on terminal background.

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  autoload -Uz is-at-least && is-at-least 5.1 || return

  # ─── Core mode ────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_MODE='nerdfont-v3'
  typeset -g POWERLEVEL9K_ICON_PADDING=none

  # ─── Basic prompt layout ──────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon       # Apple / Tux / Windows
    dir           # current directory
    vcs           # git status
    newline       # line break → prompt char on line 2
    prompt_char   # ❯
  )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code
    command_execution_time  # last command duration
    node_version            # node version when in a node project
    virtualenv              # python venv
  )

  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '

  # ─── Transient prompt ─────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # ─── Instant prompt ───────────────────────────────────────────────────────────
  # Enable in .zshrc with:
  #   if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  #     source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  #   fi

  # ─── Segment separators — NONE (clean minimal look) ──────────────────────────
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=''
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_END_SEPARATOR=''

  # ─── No background boxes — transparent backgrounds everywhere ────────────────
  # os_icon
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=231          # white
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=             # transparent
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='${P9K_CONTENT}'

  # dir
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=                 # transparent
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=39               # blue
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=39
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true            # last segment bold
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=''
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # dir — writable state colors (still no background)
  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='🔒'
  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=1   # red when not writable
  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND=

  # vcs (git)
  typeset -g POWERLEVEL9K_VCS_BACKGROUND=                 # transparent
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76         # green
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=220     # yellow
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=220    # yellow
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196   # red
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=244      # grey while loading

  # vcs — which info to show
  typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '       # nf-fa-code_fork
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='\uF417 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
  typeset -g POWERLEVEL9K_VCS_STASH_ICON='*'
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'

  # prompt_char (❯)
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76      # green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196  # red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

  # ─── Right prompt segments (all transparent) ──────────────────────────────────

  # status
  typeset -g POWERLEVEL9K_STATUS_BACKGROUND=
  typeset -g POWERLEVEL9K_STATUS_OK=false                 # hide 0 exit codes
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=196
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false

  # command_execution_time
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=248   # grey
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # node_version
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70     # green
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_NODE_ICON='\uF898 '            # nf-mdi-nodejs

  # virtualenv
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37       # teal
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  # ─── Spacing between segments ─────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  # Space between each left segment
  typeset -g POWERLEVEL9K_OS_ICON_LEFT_WHITESPACE=''
  typeset -g POWERLEVEL9K_OS_ICON_RIGHT_WHITESPACE=' '
  typeset -g POWERLEVEL9K_DIR_LEFT_WHITESPACE=''
  typeset -g POWERLEVEL9K_DIR_RIGHT_WHITESPACE=' '
  typeset -g POWERLEVEL9K_VCS_LEFT_WHITESPACE=''
  typeset -g POWERLEVEL9K_VCS_RIGHT_WHITESPACE=''

  # ─── os_icon — Apple on macOS, Tux on Linux ───────────────────────────────────
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='${P9K_CONTENT}'
  # macOS: nerdfont  (U+F179)  Linux: Tux  (U+F17C)
  # p10k auto-selects based on $OSTYPE — no manual override needed.

  # ─── Misc ─────────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_SHOW_RULER=false
  typeset -g POWERLEVEL9K_RULER_CHAR='─'
  typeset -g POWERLEVEL9K_RULER_FOREGROUND=237

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=''

  # Disable the right-side newline gap
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=237
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '

  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''

  (( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
} always {
  'builtin' 'unset' 'p10k_config_opts'
}
